name: versionist

on:
  push:
    branches:
      - "master"

jobs:
  versionist:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # requires with 'repo' access.
      # using GITHUB_TOKEN will NOT trigger other workflows
      - id: versionist
        uses: tmigone/versionist@v0.4.7
        with:
          github_email: "versionist@users.noreply.github.com"
          github_username: "versionist"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
