name: versionist

on:
  push:
    branches:
      - "master"

jobs:
  versionist:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.author.name, 'versionist')"   # Ignore push events made by the service account

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: klutchell/versionist@v0.5.0
        with:
          github_email: "versionist@users.noreply.github.com"
          github_username: "versionist"
          github_token: ${{ secrets.GH_VERSIONIST_TOKEN }}
          branch: master
